services:
  flask_app:
    container_name: api
    image: dockerhub-flask_live_app:1.0.0
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres